{% set name = "pypistats" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypistats-{{ version }}.tar.gz
  sha256: 0e0bf01f844cbd8ca57b6658a30f6f3a586c25d65c738907d991d813b3097591

build:
  entry_points:
    - pypistats = pypistats.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - urllib3 >=2
    - python >={{ python_min }}
    - httpx >=0.19
    - platformdirs
    - prettytable >=3.12
    - pytablewriter >=0.63
    - python-dateutil
    - python-slugify
    - termcolor >=3.2
    # pytablewriter[html]
    - dominate >=2.1.5,<3
    - pytablewriter >=0.63

test:
  imports:
    - pypistats
  # pytablewriter 1.2.0 has requirement tcolorpy<1,>=0.0.5, but you have tcolorpy 0.0.0.
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hugovk/pypistats
  summary: Python interface to PyPI Stats API https://pypistats.org/api
  dev_url: https://github.com/hugovk/pypistats
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
